trigger:
- main
- feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
 SANITY_AUTH_TOKEN: $(SanityDeployAPIToken)
 SANITY_STUDIO_PROJECT_BASEPATH: /studio

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
- task: CmdLine@2
  inputs:
    script: |
      npm install -g @sanity/cli
      npm install
      sanity deploy