trigger:
- main
- feature/*

pool:
  vmImage: 'ubuntu-latest'

variables:
 SANITY_AUTH_TOKEN: $(SanityDeployAPIToken)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
- task: CmdLine@2
  inputs:
    script: |
      cd src
      npm install -g @sanity/cli
      sanity login
      npm install
      sanity deploy