trigger:
- main
- feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
- task: CmdLine@2
  inputs:
    script: |
      npm install -g @sanity/cli
      npm install
      sanity deploy