name: Deploy Node.js project to Azure Function App

on:
  push:
    branches: ["master"]

env:
  AZURE_FUNCTIONAPP_NAME: 'geo-name-reverse-lookup'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './AzureFunctionDeployment'       # set this to the path to your function app project, defaults to the repository root
  NODE_VERSION: '20.0.x'                   # set this to the Node.js version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Node ${{ env.NODE_VERSION }} Environment
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: 'Resolve Project Dependencies Using Npm'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        npm install
        npm run build --if-present
        npm run test --if-present
        popd

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Update secret in Azure Key Vault
      run: |
        az keyvault secret set --vault-name ${{ vars.AZURE_KEY_VAULT_NAME }} --name ${{ vars.AZURE_KEY_VAULT_SECRET_NAME }} --value ${{ secrets.MONGO_DB_CONN_STRING }}

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} # Remove publish-profile to use Azure RBAC
        sku: flexconsumption
