name: Process and publish dataset to Mongo

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          LANGUAGES: ${{ vars.LANGUAGES }}
          POPULATION_THRESHOLD: ${{vars.POPULATION_THRESHOLD}}
          MONGO_DATABASE_NAME: ${{ vars.MONGO_DATABASE_NAME }}
          MONGO_COLLECTION_NAME: ${{ vars.MONGO_COLLECTION_NAME }}
          MONGO_DB_CONN_STRING: ${{ secrets.MONGO_DB_CONN_STRING }}
          ATLAS_API_KEY: ${{ secrets.ATLAS_API_KEY }}
          ATLAS_API_PRIVATE_KEY: ${{ secrets.ATLAS_API_PRIVATE_KEY }}
          ATLAS_CLUSTER_NAME: ${{ vars.ATLAS_CLUSTER_NAME }}
          ATLAS_SEARCH_INDEX_NAME: ${{ vars.ATLAS_SEARCH_INDEX_NAME }}
          ATLAS_GROUP_ID: ${{ secrets.ATLAS_GROUP_ID }}
        run: python countries_data.py